import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider"
import NavigationBottom from "./components/navigation-bottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ame - anime watch webapp",
    description: "Generated by create next app",
    appleWebApp: true,
    manifest: "./manifest.json"
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession();

    return (
        <html lang="en">
        <head>
            <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000000" />
            <script>
            </script>
        </head>
        <body className={`dark ${inter.className} bg-background text-foreground`}>
            <SessionProvider session={session}>
                <nav>
                    <NavigationBottom />
                </nav>
                <main className="min-h-screen w-full pb-20">
                    {children}
                </main>
            </SessionProvider>
        </body>
        </html>
    );
}
